#include <Arduino.h>
#include "preprocessor.h"
#include "decoder_init.h"

const char *getDecoderName(uint8_t decoderNum) {
  #define GET_VARIABLE_NAME(Variable) (#Variable)

  struct entity_name_map_t {
      uint8_t decoderNum;
      String name;
  };

  static const entity_name_map_t entityMap[] = {
    { DECODER_MISSING_TOOTH, GET_VARIABLE_NAME(DECODER_MISSING_TOOTH) },
    { DECODER_BASIC_DISTRIBUTOR, GET_VARIABLE_NAME(DECODER_BASIC_DISTRIBUTOR) },
    { DECODER_DUAL_WHEEL, GET_VARIABLE_NAME(DECODER_DUAL_WHEEL) },
    { DECODER_GM7X, GET_VARIABLE_NAME(DECODER_GM7X) },
    { DECODER_4G63, GET_VARIABLE_NAME(DECODER_4G63) },
    { DECODER_24X, GET_VARIABLE_NAME(DECODER_24X) },
    { DECODER_JEEP2000, GET_VARIABLE_NAME(DECODER_JEEP2000) },
    { DECODER_AUDI135, GET_VARIABLE_NAME(DECODER_AUDI135) },
    { DECODER_HONDA_D17, GET_VARIABLE_NAME(DECODER_HONDA_D17) },
    { DECODER_MIATA_9905, GET_VARIABLE_NAME(DECODER_MIATA_9905) },
    { DECODER_MAZDA_AU, GET_VARIABLE_NAME(DECODER_MAZDA_AU) },
    { DECODER_NON360, GET_VARIABLE_NAME(DECODER_NON360) },
    { DECODER_NISSAN_360, GET_VARIABLE_NAME(DECODER_NISSAN_360) },
    { DECODER_SUBARU_67, GET_VARIABLE_NAME(DECODER_SUBARU_67) },
    { DECODER_DAIHATSU_PLUS1, GET_VARIABLE_NAME(DECODER_DAIHATSU_PLUS1) },
    { DECODER_HARLEY, GET_VARIABLE_NAME(DECODER_HARLEY) },
    { DECODER_36_2_2_2, GET_VARIABLE_NAME(DECODER_36_2_2_2) },
    { DECODER_36_2_1, GET_VARIABLE_NAME(DECODER_36_2_1) },
    { DECODER_420A, GET_VARIABLE_NAME(DECODER_420A) },
    { DECODER_WEBER, GET_VARIABLE_NAME(DECODER_WEBER) },
    { DECODER_ST170, GET_VARIABLE_NAME(DECODER_ST170) },
    { DECODER_DRZ400, GET_VARIABLE_NAME(DECODER_DRZ400) },
    { DECODER_NGC, GET_VARIABLE_NAME(DECODER_NGC) },
    { DECODER_VMAX, GET_VARIABLE_NAME(DECODER_VMAX) },
    { DECODER_RENIX, GET_VARIABLE_NAME(DECODER_RENIX) },
    { DECODER_ROVERMEMS, GET_VARIABLE_NAME(DECODER_ROVERMEMS) },
    { DECODER_SUZUKI_K6A, GET_VARIABLE_NAME(DECODER_SUZUKI_K6A) },
    { DECODER_HONDA_J32, GET_VARIABLE_NAME(DECODER_HONDA_J32) },
    { DECODER_FORD_TFI, GET_VARIABLE_NAME(DECODER_FORD_TFI) },
  };
  static const constexpr entity_name_map_t* entityMapEnd = entityMap + _countof(entityMap);  

  // Linear search of the name map.
  const entity_name_map_t *pMapEntry = entityMap;
  while ((pMapEntry!=entityMapEnd) && (decoderNum!=pMapEntry->decoderNum)) {
    ++pMapEntry;
  }
  if (pMapEntry!=entityMapEnd) {
    return pMapEntry->name.c_str();
  }
  static const char *unknown = "Unknown";
  return unknown;
}
