name: Generate code coverage reports

on:
  - push
  - pull_request
  - workflow_dispatch
  
jobs:
  code-coverage:

    runs-on: ubuntu-latest

    env:
      PIO_ENV: native_code_coverage
      FILE_ROOT: speeduino_coverage
      GCOVR_EXCLUDES: >-
        --exclude test/
        --exclude lib/ArduinoFake/
        --exclude .pio/libdeps/
        --exclude speeduino/src/SPIAsEEPROM/
        --exclude '(.+/)?unity_config\.c$'
        --exclude '(.+/)?board_native\.(?:h|cpp)$'
        --exclude-throw-branches
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          cache: 'pip' # Enables caching for dependencies

    - name: Create Python venv
      run: |
        sudo apt-get install python3-venv
        python3 -m venv PIO

    - name: Install PlatformIO
      run: |
        source PIO/bin/activate
        pip install platformio
       
    - name: Run Code Coverage Tests
      # We want the coverage to reflect the status of the
      # unit tests: so even if the tests fail or outright
      # crash, continue the rest of the workflow.
      continue-on-error: true
      run: | 
        source PIO/bin/activate
        platformio test -e ${{ env.PIO_ENV }} ${{ vars.PIO_CMD_PARAMS }}

    - name: Install gcovr
      run: | 
        source PIO/bin/activate
        pip install gcovr

    - name: Generate machine readable coverage reports using gcovr CLI
      env:
        PATH_ROOT: .pio/build/${{ env.PIO_ENV }}/${{ env.FILE_ROOT }}
      run: |
        source PIO/bin/activate
        gcovr \
          ${{ env.GCOVR_EXCLUDES }} \
          --coveralls ${{ env.PATH_ROOT }}.coveralls \
          --cobertura ${{ env.PATH_ROOT }}.cobertura \
          --xml ${{ env.PATH_ROOT }}.xml \
          --jacoco ${{ env.PATH_ROOT }}.jacoco \
          --json ${{ env.PATH_ROOT }}.json \
          --lcov ${{ env.PATH_ROOT }}.lcov \
          --sonarqube ${{ env.PATH_ROOT }}.sonarqube || true
       
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v5
      env:
        PATH_ROOT: .pio/build/${{ env.PIO_ENV }}/${{ env.FILE_ROOT }}
      # if: ${{ !env.ACT }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        disable_search: true
        files: ${{ env.PATH_ROOT }}.*
        verbose: true 

    # This messes up CodeCov upload if done earlier
    - name: Generate human readable coverage reports using gcovr CLI
      if: ${{ env.ACT }}
      env:
        PATH_ROOT: .pio/build/${{ env.PIO_ENV }}/${{ env.FILE_ROOT }}
      run: |
        source PIO/bin/activate
        gcovr \
          ${{ env.GCOVR_EXCLUDES }} \
          --html-details ${{ env.PATH_ROOT }}.html \

    - name: Upload reports
      env:
        PATH_ROOT: .pio/build/${{ env.PIO_ENV }}/${{ env.FILE_ROOT }}
      if: ${{ env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.PATH_ROOT }}.*
