name: Perform MISRA scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - GH_misra

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Install cppcheck, dos2unix
      shell: bash
      run: |
        sudo apt update
        sudo apt-get -yqq install cppcheck --no-install-recommends
      #sudo apt-get install dos2unix
    
    - name: Run MISRA scan
      continue-on-error: true
      shell: pwsh
      run: |
        cd $env:GITHUB_WORKSPACE/misra/
        $NumViolations = ./check_misra.ps1 -c /usr/bin -o ./.results -q -x
        Write-Host "Scan complete"
        Write-Host "$NumViolations"
        "VIOLATIONS=$NumViolations" >> $env:GITHUB_ENV
        
    - name: Save output to Gist
      if: github.event_name != 'pull_request' && github.repository_owner == 'speeduino'
      env:
        MISRA_GIST: ${{ secrets.MISRA_GIST }}
        VIOLATIONS: ${{ env.VIOLATIONS }}
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.MISRA_GIST }}
        gistID: d8a449a3f6d3307dab457431512502f9
        filename: misra_results.json
        label: MISRA Violations
        color: red
        message: ${{ env.VIOLATIONS }}

    - name: Archive MISRA scan artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MISRA results
        path: |
          misra/.results/results.xml