name: calculate-memory-deltas

on:
  - pull_request

jobs:
  size-delta:
    env:
        BASE_FOLDER: base-code
        PR_FOLDER: pr-code
        PIO_ENVS: '["megaatmega2560", "teensy41", "black_F407VE"]'
        PR_LOG_FILE: pr-build.log
        BASE_LOG_FILE: base-build.log
        SIZE_REPORT_FILE: size_report.md
        PR_NUM_FILE: pr_number.txt

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Create Python venv
      run: |
        sudo apt-get install python3-venv
        python3 -m venv PIO

    - name: Install PlatformIO
      run: |
        source PIO/bin/activate
        pip install platformio

    - name: Build command line
      if: ${{ env.PIO_ENVS }}
      id: build_command_line
      run: |
        echo '${{ env.PIO_ENVS }}' | jq -r '.[0] |= "CMD_PIO_ENVS=-e " + . | join(" -e ")' >> $GITHUB_OUTPUT

    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        path: ${{ env.PR_FOLDER }}

    - name: Build PR Envs
      run: |
        source PIO/bin/activate
        platformio run -d ${{ env.PR_FOLDER }} ${{ steps.build_command_line.outputs.CMD_PIO_ENVS }} &> ${{ env.PR_LOG_FILE }}
    
    - name: Checkout Base Branch
      uses: actions/checkout@v4
      with:
        ref: master
        path: ${{ env.BASE_FOLDER }}

    - name: Build Base Envs
      run: |
        source PIO/bin/activate
        platformio run -d ${{ env.BASE_FOLDER }} ${{ steps.build_command_line.outputs.CMD_PIO_ENVS }} &> ${{ env.BASE_LOG_FILE }}

    - name: Generate artifacts
      run: |
        source PIO/bin/activate
        python ${{ env.PR_FOLDER }}/.github/workflows/pr-memory-deltas.py ${{ env.BASE_LOG_FILE }} ${{ env.PR_LOG_FILE }} > ${{ env.SIZE_REPORT_FILE }}
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "${{ github.event.number }}" > ${{ env.PR_NUM_FILE }}
        else
          echo "not-a-pr" > ${{ env.PR_NUM_FILE }}
        fi

    - name: Upload build logs
      if: ${{ env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        path: |
            **/*.log

      # This step is needed to pass the size data to the report job.
    - name: Upload sketches report to workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: sketches-report-all
        path: |
          ${{ env.SIZE_REPORT_FILE }}
          ${{ env.PR_NUM_FILE }}
