name: report-size-deltas

on:
  workflow_run:
    workflows: ["calculate-memory-deltas"]
    types:
      - completed

jobs:
  report:

    env:
        SIZE_REPORT_FILE: size_report.md
        PR_NUM_FILE: pr_number.txt
        SOURCE_ARTIFACT: sketches-report-all

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SOURCE_ARTIFACT }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Extract PR Number
        id: extract-pr-id
        run: |
          echo "PR_NUM<<EOF" >> $GITHUB_OUTPUT
          cat "${{ env.PR_NUM_FILE }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        if: steps.extract-pr-id.outputs.PR_NUM != 'not-a-pr'      
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ env.SIZE_REPORT_FILE }}
          comment-tag: size-report
          pr-number:  ${{ steps.extract-pr-id.outputs.PR_NUM }}
